### ISSUE TITLE
タスク削除に失敗する

### ISSUE THREAD

**Issue by bombrary** [basd4g/lovelab.heroku#26]
### 検証手順

Postmanを用いて、次のタスクを削除しようとした。

```json
{
    "id": 72,
    "groupid": 1,
    "whoisdoinguserid": 2,
    "isfinished": false,
    "name": "deleteTest",
    "comment": "test for delete",
    "deadlinedate": "2020-01-05T22:44:05.000Z",
    "finisheddate": null,
    "doneuserid": null,
    "createdAt": "2020-01-05T22:44:06.727Z",
    "updatedAt": "2020-01-05T22:44:06.727Z"
}
```
以下のURLに対して、DELETEメソッドを送った。
```
https://lovelab.2n2n.ninja/api/v1/authed/tasks/72
```
ところが、ステータスコード404のレスポンスが帰ってきて、ボディは以下のようになっていた。

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot DELETE /api/v1/authed/tasks/72</pre>
</body>

</html>
```

### その他情報

- DELETEメソッドをGETメソッドとして送信すると、タスク情報が正しく帰ってくる。そのため、Bearer Tokenは正しく設定した上で送信していると思われる。
- Bearer Tokenは「2-XXXX」のものを用いている。
- 自分が所属しているグループのタスクに対してリクエストを送っているはず。

やり方が間違っているかもしれないので、何かあれば教えてください。

**Comment by basd4g** [comment]
いま読みました！調査してみます。

**Comment by basd4g** [comment]
タスク削除は、現状、年末年始につくった新環境のみにデプロイしています。

旧環境: https://lovelab.2n2n.ninja/api/v1
新環境: http://lovelab.pw/api/v1

(旧環境と新環境では別データベース)

なので、APIManagerのURLを置き換えて、新環境にて試してみると動くかと思います。
